detector: 
  type: detectron2
  settings: 
    config_path: lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config                           # In model catalog
    label_map: 
      0: Text
      1: Title
      2: List
      3: Table
      4: Figure
    extra_config: ["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.8]
    enforce_cpu: True

ocr: 
  type: tesseract
  language: eng                   # More language can be found at: https://github.com/tesseract-ocr/langdata.git

